version: '3'

services:

  web-server:
    build:
      context: ./web
    ports:
      - 80:6000 # host : container
    volumes:
      - ./web/src:/app
    container_name: Grocery-tracker-portal

volumes:
  db:
